### ISSUE TITLE
Driverkit confused over kernel version

### ISSUE THREAD

**Issue by eelkoniovb** [falcosecurity/driverkit#291]
The driverkit I'm using in my AWS EKS environment gets confused over the version of the kernel. It's starting out fine but somewhere down the line thinks we're on kernel version 5.4 while it's running on 5.10.

Somewhere the driverkit determines the kernel version and states it's 5.4 when it's actually 5.10

I started a container with just this driverkit. This is the output:

```
/app # /app/driverkit docker --driverversion a259b4bf49c3330d9ad6c3eed9eb1a31954259a6 --kernelrelease $(uname -r) -l debug --output-probe "/work/falco_amazonlinux2_$(uname -r)_1.o" --output-module "/work/falco_amazonlinux2_$(u
name -r)_1.ko" -t amazonlinux2 -i my-repository.foo.bar/falcosecurity/driverkit-builder:custom
DEBU running without a configuration file         
DEBU running with options                          driverversion=a259b4bf49c3330d9ad6c3eed9eb1a31954259a6 kernelrelease=5.10.192-183.736.amzn2.x86_64 kernelversion=1 output-module=/work/falco_amazonlinux2_5.10.192-183.736.amzn2.x86_64_1.ko output-probe=/work/falco_amazonlinux2_5.10.192-183.736.amzn2.x86_64_1.o target=amazonlinux2
INFO driver building, it will take a few seconds   processor=docker
DEBU doing a new docker build                     
DEBU looking for repo...                           url="http://amazonlinux.eu-central-1.amazonaws.com/2/core/2.0/x86_64/mirror.list" version=core/2.0
DEBU downloading...                                url="http://amazonlinux.eu-central-1.amazonaws.com/2/core/2.0/x86_64/eb72ea01ca029aaf7a15e5b987f6bee895bae6c7ef9f3bd009d8a3181c6e78c8/repodata/primary.sqlite.gz"
DEBU connecting to database...                     db=/tmp/amazonlinux2-385404239.sqlite
DEBU looking for repo...                           url="http://amazonlinux.eu-central-1.amazonaws.com/2/core/latest/x86_64/mirror.list" version=core/latest
DEBU looking for repo...                           url="http://amazonlinux.eu-central-1.amazonaws.com/2/extras/kernel-5.4/latest/x86_64/mirror.list" version=extras/kernel-5.4/latest
DEBU downloading...                                url="http://amazonlinux.eu-central-1.amazonaws.com/2/extras/kernel-5.4/stable/x86_64/1d0fb871c089c19684ea44ddc94b0ba6ec91b68ae7e49c7e3c94ff08adc8f86f/repodata/primary.sqlite.gz"
DEBU connecting to database...                     db=/tmp/amazonlinux2-42905234.sqlite
FATA exiting                                       error="target amazonlinux2 needs to find both kernel and kernel-devel packages"
```

You can see that in the fourth line before the end it's mentioning kernel-5.4 while nothing points to that. Uname also hands out 5.10 every time you query it.

The AWS sqlite databases that are downloaded do contain entries for kernel 5.10 but none for 5.4 - so the driverkit thinks the database has no valid entries. But it does.

I expect the driverkit to correctly work with version 5.10 instead of 5.4

**Environment**

- Falco driverkit version: "driverkit version -+"
- System info: Kubernetes
- Cloud provider or hardware configuration: AWS
- OS: Linux 
- Kernel: 5.10.192-183.736.amzn2.x86_64
- Installation method: Kubernetes

**Comment by FedeDP** [comment]
Hi! Thanks for opening this bug report.
Can you share your `uname -a` output?

**Comment by FedeDP** [comment]
> driverkit version -+

Mmh? :D Can you try to upgrade to latest version?

**Comment by FedeDP** [comment]
With v0.15.0 i am able to trigger the driver build, even if it then fails:
> level=DEBUG msg="\x02\x00\x00\x00\x00\x00\x00\xba/tmp/driver/main.c:1875:41: error: invalid use of undefined type 'struct timespec'\n"
level=DEBUG msg=" 1875 |                 ring->last_print_time = *ts;\n"

Most probably, the driverversion you are using did not support kernels 5.10 (it is super ancient version from ~3.5yrs ago)

**Comment by eelkoniovb** [comment]
Thanks for your help, FedeDP!

We are indeed now working towards a new driverkit but also to an eBPF based Falco, which seems to be the one that's less intrusive to the nodes. Though I have a warm heart whenever I see something compiling, I think we'll be moving on to the ePBF version. ;) 

If that doesn't work, we'll definitely update the driverkit, which we've been using for quite some time - as you noticed. ;)

**Comment by FedeDP** [comment]
> We are indeed now working towards a new driverkit but also to an eBPF based Falco, which seems to be the one that's less intrusive to the nodes. Though I have a warm heart whenever I see something compiling, I think we'll be moving on to the ePBF version. ;)

Do you mean using hte `modern-bpf` driver that does not require any external artifact? Yep that's the most future proof choice :)
